# SwiftLint Configuration for Listener Pro
# Optimized for SwiftUI and modern Swift development

# Paths to include for linting
included:
  - listener/

# Paths to exclude from linting
excluded:
  - build/
  - DerivedData/
  - .build/
  - Pods/
  - listener/Preview Content/

# Disable certain rules that don't fit our SwiftUI patterns
disabled_rules:
  - trailing_whitespace # Can be auto-fixed
  - large_tuple # SwiftUI uses tuples extensively
  - file_header # Too strict for existing codebase, enable gradually
  - multiple_closures_with_trailing_closure # SwiftUI patterns conflict

# Configure specific rules
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

# Opt-in rules (enable additional helpful rules)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rules
custom_rules:
  # Encourage use of design system colors (but not in design system files themselves)
  design_system_colors:
    name: "Use Design System Colors"
    regex: '\.blue|\.red|\.green|\.gray|\.orange|\.yellow|\.purple|\.pink'
    match_kinds:
      - identifier
    message: "Consider using design system colors from Colors.swift instead of system colors"
    severity: warning
    excluded:
      - ".*DesignSystem/.*"

  # Encourage use of design system typography (but not in design system files themselves)
  design_system_typography:
    name: "Use Design System Typography"
    regex: '\.font\(\.title\)|\.font\(\.headline\)|\.font\(\.body\)|\.font\(\.caption\)'
    match_kinds:
      - identifier
    message: "Consider using design system typography modifiers like .appTitle(), .appHeadline(), etc."
    severity: warning
    excluded:
      - ".*DesignSystem/.*"

# File header template (disabled for now, enable gradually)
# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*\.swift
#                     \/\/  listener
#                     \/\/
#                     \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2,4}\.
#                     \/\/

# Identifier name rules
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - URL
    - x
    - y
    - z
    - conversation_id
    - speaker_id
    - utterance_id
    - created_at
    - display_name
    - speaker_count
    - utterance_count
    - total_duration
    - start_time
    - end_time
    - start_ms
    - end_ms
    - audio_url
    - speaker_name
    - pinecone_speaker_name
    - included_in_pinecone
    - utterance_embedding_id
    - embedding_id
    - date_processed
    - duration_seconds

# Type name rules
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Reporter type
reporter: "xcode"